version: '3'

services: 
    web:
        image: nginx
        ports: 
            - '8080:80'
        depends_on: 
            - app
        volumes: 
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html

    app:
        build: ./docker/php
        volumes: 
            - ./src:/var/www/html
        depends_on: 
            - mysql
    
    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo
        ports: 
            - "3306:3306"
        volumes: 
            - ./docker/mysql/data:/var/lib/mysql